### ISSUE TITLE
FEATURE - Can't rob if not enough cops on

### ISSUE THREAD

**Issue by BobbyLinny** [Sighmir/vrp_holdup#1]
Make it so you can't rob a store or bank if there is not enough cops online.

**Comment by Sighmir** [comment]
This script is intended for PvE use with the game cops enabled, I will make a fork in the future for PvP without the NPCs wanted level and a check for online cops. Thank you or the sugestion. I will leave this open until I have time to work on GTA V scripts again, I am really busy for the next 4 months so dont expect it any time soon.

**Comment by BobbyLinny** [comment]
Ok, I have wanted level disabled which is why this would really be essential. Can't wait till you get back to GTA 5 scripting :)

**Comment by Danishflipper** [comment]
Hi, is it possible to ad Pacific standard bank as a holdup???

**Comment by Sighmir** [comment]
You can configure banks on server.lua and client.lua. 
"Can't rob if not enough cops on" has been added on the new PvP update.
