### ISSUE TITLE
Cannot implement vRP.hasPermission to avoid Police and E.M.S. starting robberies

### ISSUE THREAD

**Issue by NoxOverFlow** [Sighmir/vrp_holdup#2]
I am trying to put "vRP.hasPermission" inside the server.lua of the script to prevent Police and E.M.S. members to start a robbery. I just replaced the last robbery timer check with the permission check, the EventHandler looks like this.

`RegisterServerEvent('es_holdup:rob')
AddEventHandler('es_holdup:rob', function(robb)
	if stores[robb] then
		local store = stores[robb]
                local vrp_user_id = vRP.getUserId(source)

		if vRP.hasPermission(vrp_user_id,"emergency.jobs") then
			TriggerClientEvent('chatMessage', source, 'RAPINA', {255, 0, 0}, "Police and E.M.S. cannot start robberies!")
			return
            end
		TriggerClientEvent('chatMessage', -1, 'P.S.A.', {255, 0, 0}, "Rapina in corso a ^2" .. store.nameofstore)
		TriggerClientEvent('chatMessage', source, 'RAPINA', {255, 0, 0}, "Hai iniziato una rapina a ^2" .. store.nameofstore .. "^0, non allontanarti troppo altrimenti fallirai!")
		TriggerClientEvent('chatMessage', source, 'RAPINA', {255, 0, 0}, "Proteggi questo luogo per ^12 ^0minuti dalla Polizia e la refurtiva sara' tua!")
		TriggerClientEvent('es_holdup:currentlyrobbing', source, robb)
		stores[robb].lastrobbed = os.time()
		robbers[source] = robb
		local savedSource = source
		SetTimeout(120000, function()
			if(robbers[savedSource])then
				local user_id = vRP.getUserId({savedSource})
				if(user_id)then
					vRP.giveInventoryItem({user_id,"dirty_money",store.reward,true})
					TriggerClientEvent('chatMessage', -1, 'NEWS', {255, 0, 0}, "Rapina terminata con successo a ^2" .. store.nameofstore .. "^0, i rapinatori hanno ottenuto la refurtiva.")
					TriggerClientEvent('es_holdup:robberycomplete', savedSource, store.reward)
				end
			end
			
		end)
		
	end
end)`

It doesn't give me any console errors, but whenever I try to start the robbery (with or without the 'emergency.jobs' permission) the "Robbery in progress" text shows and the console gets spammed with this.

`Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: [string "-- Proxy interface system, used to add/call f..."]:39: bad argument #1 to 'unpack' (table expected, got number)
stack traceback:
        [C]: in function 'table.unpack'
        [string "-- Proxy interface system, used to add/call f..."]:39: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:124: in function citizen:/scripting/lua/scheduler.lua:123
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:123: in function citizen:/scripting/lua/scheduler.lua:92`

What can I do to resolve this?

**Comment by Sighmir** [comment]
Please do not create issues asking for help to modify the code, the issue here is not related to my resource. You are using the vRP API wrongly, read the documentation at the Imagic's vRP GitHub page.

_Sent from my Samsung SM-G900M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
